Feature/dependency call abstraction
allegro/dotnet-utils pull request #21
Opened 2023-06-21 13:07 UTC by ppiwow-apay

2023-06-22 08:48 UTC, darthkurak reviewed
Seems almost right. Have few questions.

2023-06-22 08:48 UTC, darthkurak commented on src/Allegro.Extensions.DependencyCall/README.md
> +    public void Executed(IRequest request);
Wouldn't be better call it Succeeded?

2023-06-22 08:48 UTC, darthkurak commented on src/Allegro.Extensions.DependencyCall/README.md
> +- app1_dependency_call_duration_metrics_sum
only used_total has label status? I understood that there will be other status like Failed, Fallback etc? 
What status will be if our call timeout?

2023-06-22 08:48 UTC, darthkurak commented on src/Allegro.Extensions.DependencyCall/README.md
> +**Call timeout**
Does call timeout trigger fallback? Or only a failure?

2023-06-22 08:48 UTC, darthkurak commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall.Metrics.Prometheus/PrometheusDependencyCallMetrics.cs
> +    private static Counter DependencyCallCounterFactory(IMetricFactory metrics, string applicationName) =>
I don't get it why we need a both? 
Histogram also provides counter

2023-06-22 08:48 UTC, darthkurak commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall.Metrics.Prometheus/PrometheusDependencyCallMetrics.cs
> +    private static Counter DependencyCallCounterFactory(IMetricFactory metrics, string applicationName) =>
```
A histogram with a base metric name of <basename> exposes multiple time series during a scrape:

cumulative counters for the observation buckets, exposed as <basename>_bucket{le="<upper inclusive bound>"}
the total sum of all observed values, exposed as <basename>_sum
the count of events that have been observed, exposed as <basename>_count (identical to <basename>_bucket{le="+Inf"} above)
```

2023-06-22 08:48 UTC, darthkurak commented on src/Allegro.Extensions.DependencyCall/README.md
> +By default, we deliver `NoOppDependencyCallMetrics` that might be replaced with your own metrics solution with
NoOpp? What does it means?

2023-06-22 08:52 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/README.md
> +- app1_dependency_call_duration_metrics_sum
yes, will be all, just sample here

2023-06-22 08:53 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/README.md
> +**Call timeout**
yep, fallback will be triggered if supported, if fallback logic will return that not able to handle failed will be triggered, this logic is checked in tests

2023-06-22 08:54 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall.Metrics.Prometheus/PrometheusDependencyCallMetrics.cs
> +    private static Counter DependencyCallCounterFactory(IMetricFactory metrics, string applicationName) =>
to be honest, not sure, my lack of knowledge probably, and maybe a kind of opti I guess?

2023-06-22 08:55 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/README.md
> +By default, we deliver `NoOppDependencyCallMetrics` that might be replaced with your own metrics solution with
NoOpperation :D i just borrowed naming from https://github.com/App-vNext/Polly/blob/main/src/Polly/NoOp/AsyncNoOpPolicy.cs but add to many P :D

2023-06-22 08:56 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/README.md
> +By default, we deliver `NoOppDependencyCallMetrics` that might be replaced with your own metrics solution with
ranamed it to NoOperationDependencyCallMetrics

2023-06-22 08:57 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/README.md
> +    public void Executed(IRequest request);
maybe, not sure

2023-06-22 14:22 UTC, BartoszChrostowski submitted a review, later dismissed

2023-06-22 14:22 UTC, BartoszChrostowski commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +    protected virtual IAsyncPolicy<TResponse> CustomPolicy(CancellationToken cancellationToken) =>
One does not need `CancellationToken` when building Policy. The polly implementation provides overloads which pass the cancellationToken to the delegates in policy, which was used when calling the policy.

```cs
policy.ExecuteAsync(token => Execute(request, token), cancellationToken <--- );
```

2023-06-22 14:22 UTC, BartoszChrostowski commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +#pragma warning disable MA0049
Quite unfortunate. Have you considered changing the name of the class to something else to avoid confusion?
For generic types, it is not a big deal, but still. It does not look good if you were to use full class names with namespaces.

2023-06-22 14:47 UTC, BartoszChrostowski commented on src/Allegro.Extensions.DependencyCall/README.md
> +By default, we assume that operations longer than **5 seconds** from the user perspective are too long and the call will be canceled after this time.
It is not true when `cancellationToken is not null`

2023-06-22 14:47 UTC, BartoszChrostowski commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +            var fallbackValue = await Fallback(request, exception, cancellationToken.Value);
I would consider checking `IsCancellationRequested` before calling Fallback method. The `exception` may be `OperationCanceledException`

2023-06-22 14:47 UTC, BartoszChrostowski commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +                dependencyCallMetrics.Failed(request, exception);
`Failed` metric is not called when Fallback throws, because exceptions are not handled for Fallback.

2023-06-22 15:49 UTC, BartoszChrostowski commented on src/Allegro.Extensions.DependencyCall/README.md
> +**Call timeout**
> fallback will be triggered if supported

U sure? Given that the CancellationToken will be requesting cancellation at that point, the expected behaviour of the Fallaback will be throwing OperationCancelledException (Or to pass ShouldThrowOnError.Yes).

2023-06-22 15:49 UTC, BartoszChrostowski commented on src/Allegro.Extensions.DependencyCall/README.md
> +By default, we deliver `NoOppDependencyCallMetrics` that might be replaced with your own metrics solution with
Update README too 🙏

2023-06-22 18:26 UTC, BartoszChrostowski commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +        using var cancellationTokenSource = new CancellationTokenSource();
I would really advice using [Timeout from Polly with pessimistic mode](https://github.com/App-vNext/Polly/wiki/Timeout#pessimistic-timeout).

When one respects cancellationToken it uses cancellationToken however, it can timeout even if the called delegate does not respect the cancellationToken with no extra cost:
> For asynchronous executions, the extra resource cost is marginal

2023-06-22 18:26 UTC, BartoszChrostowski commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCallDispatcher.cs
> +            throw new MissingMethodException($"Missing method Run in dependency call for request {request.GetType().FullName}");
Is this even possible? The interface forces the implementation.

2023-06-22 20:08 UTC, BartoszChrostowski commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +    protected virtual IAsyncPolicy<TResponse> CustomPolicy(CancellationToken cancellationToken) =>
Additionally it may lead to unexpected behavior, for example for Timout policy.

2023-06-23 08:37 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/README.md
> +**Call timeout**
yes, i'm sure, there is event test for that:

2023-06-23 08:37 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/README.md
> +**Call timeout**
public async Task Default_timeout_should_be_set_for_cacnellation()

2023-06-23 08:38 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall.Metrics.Prometheus/PrometheusDependencyCallMetrics.cs
> +    private static Counter DependencyCallCounterFactory(IMetricFactory metrics, string applicationName) =>
fixed, only histogram is used

2023-06-23 08:39 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/README.md
> +By default, we deliver `NoOppDependencyCallMetrics` that might be replaced with your own metrics solution with
thanks, done

2023-06-23 08:40 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +        CancellationToken? cancellationToken)
this is because of api of dispatcher:

2023-06-23 08:44 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +        cancellationToken ??= cancellationTokenSource.Token;
good point,

not sure how to override token that is passed from request, not sure if I want too, but for sure need to think about the issue that cancel after override is silently ingored.

2023-06-23 08:45 UTC, BartoszChrostowski commented on src/Allegro.Extensions.DependencyCall/README.md
> +**Call timeout**
Yes but if somebody is to implement
```cs
protected override Task<(ShouldThrowOnError ShouldThrowOnError, SellerInfo Response)> Fallback(...)
=> (ShouldThrowOnError.No, await _httpClient(request, cancellationToken);
```
The httpClient will throw on CancellationToken (and we will loose the stack of the cancellationException thrown from main `Execute(...)` path)

2023-06-23 08:45 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +        Undefined = 0,
right, just copy passed from tempalte where it was like that. fixed

2023-06-23 08:47 UTC, BartoszChrostowski commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +        CancellationToken? cancellationToken)
`CancellationToken? cancellationToken = null`
Can be changed to 
`CancellationToken cancellationToken = default`
where `default` is the same as `CancellationToken.None`

And it is the recommended way of doing it.

2023-06-23 08:52 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +        var policy = CustomPolicy(cancellationToken.Value);
build? it rather depends on user, for now it just get the instance of policy, but maybe i'dont understand.

you are able just to override policy in way you want, so you can have static if you want.

2023-06-23 09:17 UTC, BartoszChrostowski commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +        var policy = CustomPolicy(cancellationToken.Value);
In README you provide an example:

```c#
protected override IAsyncPolicy<SampleResponseData> CustomPolicy(CancellationToken cancellationToken)
{
    return Policy<SampleResponseData>.Handle<Exception>().FallbackAsync(
        token =>
        {
            return Task.FromResult(new SampleResponseData("Fallback value"));
        });
}
```

which is missleading.

Making `CustomPolicy` a virtual get property would better catch the intention of API since it may guide the user towards caching the AsyncPolicy in static field (or in some kind of registry that would provide singletons) since in guidelines of C#
> Properties are meant to be used like fields, meaning that properties should not be computationally complex or produce side effects

However the whole approach of virtual methods is questionable, since it would be allways easy to implement Policy in such a way that it is not a single instance. I believe the API should force that.

2023-06-23 09:30 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +            if (fallbackValue.ShouldThrowOnError == ShouldThrowOnError.Yes)
to be honest, i understand but not sure if there is any problem to be solved here.

yes you can do that:
` var result = await _someFallbackApi.SomeVeryLongRunningQuery(params);
    return (ShouldThrowOnError.Yes, result);`

would you? ok this is possible. if this is true issue? Don't think so.

i could change but it means small braking change for those who already used. will think, thanks

2023-06-23 09:33 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/README.md
> +**Call timeout**
to be honest, i don't think if there is potential to use external call for fallback, seems strange, exception is passed to fallback so we can check what was that.
i theory yes, but to be honest in practice not sure if we have issue here.

2023-06-23 09:34 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +#pragma warning disable MA0049
could you point what name? as i can;t figure it out from comment.

2023-06-23 09:37 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/README.md
> +By default, we assume that operations longer than **5 seconds** from the user perspective are too long and the call will be canceled after this time.
yes, you point that in different comment, could try to change behavior with Polly for timeout instead of cancellation toke, will reconsider it

2023-06-23 09:38 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +                dependencyCallMetrics.Failed(request, exception);
you assume that fallback will be mostly calling other apis, I assume that some precofigured value should be returned, but yes, you are right

2023-06-23 09:39 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +        using var cancellationTokenSource = new CancellationTokenSource();
yes, will think about it. thanks

2023-06-23 09:39 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCallDispatcher.cs
> +            throw new MissingMethodException($"Missing method Run in dependency call for request {request.GetType().FullName}");
just double check. but yes, probably not possible

2023-06-23 12:21 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/README.md
> +**Call timeout**
changed to polly and cancellation token default just passed to methods

2023-06-23 12:38 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +                dependencyCallMetrics.Failed(request, exception);
added tryFallback with wrapping both errors in one if error appears

2023-06-23 12:40 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +        using var cancellationTokenSource = new CancellationTokenSource();
done

2023-06-23 12:40 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +            var fallbackValue = await Fallback(request, exception, cancellationToken.Value);
added

2023-06-23 12:41 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +        cancellationToken ??= cancellationTokenSource.Token;
switched to polly aproach

2023-06-23 13:15 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +            if (fallbackValue.ShouldThrowOnError == ShouldThrowOnError.Yes)
done

2023-06-23 13:21 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +        var policy = CustomPolicy(cancellationToken.Value);
not sure how to foce that to be honest. Even
`return Policy.TimeoutAsync<TResponse>(CancelAfter, TimeoutStrategy.Pessimistic).WrapAsync(customPolicy);`
I have variable, that might change case by case. I could register dependency as signleton and just build policy once at the first start, but not sure if it solve "forcing" issue. But singleton might be tricky in some cases to.

2023-06-23 13:39 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +        var policy = CustomPolicy(cancellationToken.Value);
i changed some thing, NoOp is now static, change from method to property rather, changed documentation to show usage of static policy, not sure what I can do more

2023-06-23 14:09 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +        var policy = CustomPolicy(cancellationToken.Value);
i added in memory concurent dictionary cache, and extended readme and summaries, to inform that this is used only once.

2023-06-26 11:33 UTC, rafalschmidt97 requested changes

2023-06-26 11:33 UTC, rafalschmidt97 commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +            var response = await policy.ExecuteAsync(token => Execute(request, token), cancellationToken);
Tutaj się upewnij, że na pewno dobrze robisz. Pamietam, że kiedyś mieliśmy z tym problem i coś pokroju tego było poprawne:

```
            var response = await policy.ExecuteAsync(async token => {   
                using var linkedTokenSource = CancellationTokenSource.CreateLinkedTokenSource(
                    pollyCancellationToken,
                    requestCancellationToken);
                    
                  await Execute(request, linkedTokenSource.Token)
              }, 
              // None here indicates missing independent cancellation control and
              // cancellation will be provided by TimeoutPolicy.
              CancellationToken.None);
                    
```

2023-06-26 11:36 UTC, rafalschmidt97 commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall.Abstractions/IDependencyCallMetrics.cs
> +    public void Failed(IRequest request, Exception exception, Stopwatch timer);
`Failed` - mam wrażenie, że to się nigdy nie powinno wydarzyć

2023-06-26 11:40 UTC, rafalschmidt97 commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall.Metrics.Prometheus/PrometheusDependencyCallMetrics.cs
> +        metrics.CreateHistogram(
Nie chcemy tutaj podać  bucketów samemu?

```
                        0.05d, // 50 s
                        0.1d, // 100 s
                        1d, // 1 s
                        5d,
                        10d, // 10 s
                        15d,
                        30d,
                        60d, // 1m
```

2023-06-26 21:51 UTC, rafalschmidt97 approved these changes
Consider polly based pnly dependency call:
https://github.com/allegro/dotnet-utils/pull/22

2023-06-26 21:54 UTC, rafalschmidt97 commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +    protected virtual IAsyncPolicy<TResponse> CustomPolicy(CancellationToken cancellationToken) =>
<img width="747" alt="image" src="https://github.com/allegro/dotnet-utils/assets/14861637/1e573ca9-2e47-41db-bb00-71b355e1bf04">

2023-06-27 06:10 UTC, rafalschmidt97 commented
Proponuje dopisanie testu na jakiś custom polly policy typu WaitAndReply

2023-06-27 10:59 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +#pragma warning disable MA0049
oh, that we have namespace and class like DependencyCall.DependencyCall... mhm

2023-06-27 11:08 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +#pragma warning disable MA0049
i understand, but if pluralizing is better? not sure... and can't find anything better tbh. will leave it as it is

2023-06-27 11:12 UTC, ppiwow-apay commented on global.json
>          "version": "6.0.100",
ok

2023-06-27 11:25 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/README.md
> +            return Task.FromResult(FallbackResult.NotSupported);
FallbackResutl is only the way of returning consistent results from fallback. We should avoid situation that might be misleading like returning some FallbackResult with info that it not supports fallbacks.

This library is not only for fallbacks, is rather to standardized way of calling dependencies and make you think of some common concerns like fallbacks, timeouts, transient errors and to abstract technical implementation from business usage.

2023-06-27 11:26 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +namespace Allegro.Extensions.DependencyCall;
i really not wanted to use polly but it is so common library that it is hard to use something else and prepare abstraction for it and put default polly implementation in separate library. maybe we could think about it in future if we have our own or more commonly use library than polly

2023-06-27 11:29 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +            var response = await policy.ExecuteAsync(token => Execute(request, token), cancellationToken);
do you remember what was the issue? i want to pass original cancellation token to client. how should i create `pollyCancellationToken` and when

2023-06-27 11:36 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall.Metrics.Prometheus/PrometheusDependencyCallMetrics.cs
> +        metrics.CreateHistogram(
50s? i hope that we don't have this kind of requests. default seems pretty good:

2023-06-27 12:01 UTC, BartoszChrostowski commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCall.cs
> +            var response = await policy.ExecuteAsync(token => Execute(request, token), cancellationToken);
For what i have seen the situation Rafal describes was quite different. This should be perfectly fine.

2023-06-27 13:12 UTC, darthkurak approved these changes
Kilka drobnych uwag

2023-06-27 13:12 UTC, darthkurak commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCallDispatcher.cs
> +            // TODO: throw this on startup
jakiś todo został

2023-06-27 13:12 UTC, darthkurak commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall.Abstractions/IDependencyCallMetrics.cs
> +    public void Succeeded(IRequest request, Stopwatch timer);
Może TimeSpan zamiast Stopwatch? ;)

2023-06-27 13:12 UTC, darthkurak commented on src/Allegro.Extensions.DependencyCall/README.md
> +public interface IDependencyCallMetrics
Upewnij się, że dokumentacja jest up to date ze zmianami po review, bo tutaj w IDependencyCallMetrics nie jest.

2023-06-27 13:12 UTC, darthkurak commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/NoOperationDependencyCallMetrics.cs
> +    public void Total(IRequest request, Stopwatch timer)
W interfejsie nie ma Total

2023-06-28 07:20 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/DependencyCallDispatcher.cs
> +            // TODO: throw this on startup
this is note for future, that maybe consider to throw this on startup (validate if all calls has commands) rather on runtime. rephrased it

2023-06-28 07:21 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall.Abstractions/IDependencyCallMetrics.cs
> +    public void Succeeded(IRequest request, Stopwatch timer);
done

2023-06-28 07:22 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/Allegro.Extensions.DependencyCall/NoOperationDependencyCallMetrics.cs
> +    public void Total(IRequest request, Stopwatch timer)
yes, removed that, thanks

2023-06-28 07:24 UTC, ppiwow-apay commented on src/Allegro.Extensions.DependencyCall/README.md
> +public interface IDependencyCallMetrics
done

2023-06-29 08:50 UTC, merged