Fluent config validation
allegro/dotnet-utils pull request #8
Opened 2022-11-10 11:57 UTC by sowa705

API for complex fluent validators

2022-11-10 12:23 UTC, ppiwow-apay commented
would like to see some examples in readme at least - if possible please describe in readme previous thing and add usage examples of this Options validation please

2022-11-17 08:12 UTC, darthkurak requested changes

2022-11-17 08:12 UTC, darthkurak commented on src/Allegro.Extensions.Validators/Allegro.Extensions.Validators/OptionsBuilderFluentValidationExtensions.cs
> +    /// Adds a scoped IValidateOptions&lt;TOptions&gt; service with fluent validation.
we add as singleton, and summary tells about scoped

2022-11-17 08:12 UTC, darthkurak commented on src/Allegro.Extensions.Validators/Allegro.Extensions.Validators/StartupExtensions.cs
> +        services.AddSingleton<IValidator<TOptions>, TValidator>();
should be scoped?

2022-11-17 08:12 UTC, darthkurak commented on src/Allegro.Extensions.Validators/README.md
> +Create IOptions<T> with fluent validation enabled
missing example of ValidateFluentValidation

2022-11-17 11:50 UTC, darthkurak approved these changes

2022-11-17 12:39 UTC, orgiele requested changes

2022-11-17 12:39 UTC, orgiele commented on src/Allegro.Extensions.Validators/Allegro.Extensions.Validators/FluentValidationOptions.cs
> +        // Run the validation
część tych komentarzy IMHO niewiele wnosi

2022-11-17 12:39 UTC, orgiele commented on src/Allegro.Extensions.Validators/Allegro.Extensions.Validators/FluentValidationOptions.cs
> +using System;
jeżeli to jest kod skopiowany z jakiejś strony, to imho wypadałoby to zaznaczyć w jakimś komentarzu

2022-11-17 12:39 UTC, orgiele commented on src/Allegro.Extensions.Validators/Allegro.Extensions.Validators/StartupExtensions.cs
> +    public static OptionsBuilder<TOptions> AddWithFluentValidation<TOptions, TValidator>(
AddWith brzmi dziwnie, albo Add albo With 😁

2022-11-17 12:51 UTC, sowa705 commented on src/Allegro.Extensions.Validators/Allegro.Extensions.Validators/StartupExtensions.cs
> +    public static OptionsBuilder<TOptions> AddWithFluentValidation<TOptions, TValidator>(
może AddOptionsWithFluentValidation?

2022-11-17 15:16 UTC, merged